#!/bin/bash
# Administer back-end Fairplay services

# Usage:
# To start:
#   ./fairplay_servers
# To stop:
#  ./fairplay_server stop
# To show running services:
#  ./fairplay_server show 

if [ -n "${JAVA_HOME}" ]; then
  JAVA=${JAVA_HOME}/bin/java
else
  JAVA=java
fi

## 
# Reset logs
function reset_log {
  :> data/bob3490.log
  :> data/alice3491.log
  :> data/bob3492.log
  :> data/alice3493.log
}

# start all services
function start_services {
  ${JAVA} -Drundir=run/ -classpath MetaAnalysis.jar edu.vanderbilt.hiplab.metaanalysis.BobService 3490  >> data/bob3490.log &
  ${JAVA} -Drundir=run/ -classpath MetaAnalysis.jar edu.vanderbilt.hiplab.metaanalysis.AliceService 3491  >> data/alice3491.log &
  
  ${JAVA} -Drundir=run/ -classpath MetaAnalysis.jar edu.vanderbilt.hiplab.metaanalysis.BobService 3492  >> data/bob3492.log &
  ${JAVA} -Drundir=run/ -classpath MetaAnalysis.jar edu.vanderbilt.hiplab.metaanalysis.AliceService 3493  >> data/alice3493.log &
}

# stop all services
function stop_services {
  netstat -lpn | grep '/java' | grep :349 | tr -s ' ' | cut -d' ' -f7 | sed 's|/java||g' | xargs kill
}

function show_services {
  netstat -antp | grep :349 | grep '/java'
}


if [ $# -eq 0 ]; then
  echo "> To start services..."
  reset_log
  start_services

  sleep 2
  show_services
elif [ $1 == "show" ]; then
  show_services
elif [ $1 == "stop" ]; then
  echo "Stopping all services..."
  stop_services
  
  sleep 2
  show_services
fi
