#!/bin/bash

# Run experiment in one command
# Usage:
#   ./start <verify>

if [ -n "${JAVA_HOME}" ]; then
  JAVA=${JAVA_HOME}/bin/java
else
  JAVA=java
fi

${JAVA} -Drundir=run/ -jar MetaAnalysis.jar main.Owner $*
