#!/bin/bash

# Run experiment in one command
# Usage:
#   ./start

if [ -n "${JAVA_HOME}" ]; then
  JAVA=${JAVA_HOME}/bin/java
else
  JAVA=java
fi

${JAVA} -Xms1g -Xmx2g -Drundir=run/ -jar MetaAnalysis.jar main.Experiment
