#!/bin/bash

# Run experiment in one command
# Usage:
#   ./start

if [ -n "${JAVA_HOME}" ]; then
  JAVA=${JAVA_HOME}/bin/java
else
  JAVA=java
fi

function prepare_data(){
  ${JAVA} -Drundir=run/ -classpath MetaAnalysis.jar edu.vanderbilt.hiplab.metaanalysis.Owner "verify"
}

## Prepare data
prepare_data > data/verification.log
sleep 5

## Run experiment
${JAVA} -Xms800m -Xmx2g -Drundir=run/ -classpath MetaAnalysis.jar edu.vanderbilt.hiplab.metaanalysis.Experiment > data/experiment.log
